version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network

  mysql:
      image: mysql:5.7
      command: --innodb-use-native-aio=0 --init-file /data/application/init.sql
      container_name: mysql
      restart: always
      tty: true
      volumes:
        - ./mysql/init.sql:/data/application/init.sql
      environment:
        - MYSQL_DATABASE=nodedb
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
      networks:
        - app-network

networks:
  app-network:
    driver: bridge  
